### PR TITLE
fix git file type

### PR DESCRIPTION
**Pull request by zpcore**
Resolved https://github.com/airockchip/rknn-toolkit2/issues/65

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
Really should just be replaced with correct symbolic links, which git does support for a long time. I don't know why you insist to duplicate the same file.

**Comment by zpcore** [comment]
> Really should just be replaced with correct symbolic links, which git does support for a long time. I don't know why you insist to duplicate the same file.

Hmm, it doesn't duplicate. This PR replaces the symbol with the content directly so users don't need to fix the symbol by themselves.

**Comment by RadxaYuntian** [comment]
The point of symbolic link is when library needs to be updated it only needs to be updated once. There is also now 3 copies of the same file which increase the repository size unnecessarily.

Unsub‘d from this PR.

**Comment by zpcore** [comment]
I got what you mean here. Thanks for the clarification.

**Pull request closed without merging**
